name: Metrics
on:
  schedule: [{ cron: "0 20 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          user: Slinet6056
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: Asia/Shanghai
          config_display: regular

          plugin_achievements: no
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_languages_other: yes
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, languages, languages-graphs, editors, editors-graphs
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: Slinet6056

          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: 缄默线, Slinet6056, Slinet6056@users.noreply.github.com
          plugin_languages_ignored: >-
            tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, Rich Text Format, Limbo, SVG, JSON, XML, Gradle, YAML, ini
          plugin_languages_sections: most-used
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 6
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: data, markup, programming
          plugin_languages_colors: github
          plugin_languages_other: no
          plugin_languages_recent_categories: data, markup, programming
          plugin_languages_recent_days: 0
          plugin_languages_recent_load: 1000
          plugin_languages_threshold: 0%

          plugin_steam: no
          plugin_steam_achievements_limit: 0
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: SlinetX
