name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          user: Slinet6056
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          config_display: regular

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

          plugin_gists: no

          plugin_pagespeed: no
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://slinet.cn

          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_languages_other: yes
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, languages, languages-graphs, editors, editors-graphs
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: Slinet6056

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

          plugin_languages: yes
          plugin_languages_ignored: >-
            Rich Text Format
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 5
          plugin_languages_analysis_timeout: 15
